### ISSUE TITLE
ability for edit user

### ISSUE THREAD

**Issue by mohammad-rj** [hoppler/SoftEtherApi-PHP#5]
Thank you for your efforts
plz add ability for edit user

**Comment by hoppler** [comment]
thats whats setUser is for.
```php
$t = getUser("testUser");
$t->name = "test";
setUser($t);
```

**Comment by mohammad-rj** [comment]
$user = $softEther->HubApi->getUser("vpn", "test5");

**Comment by hoppler** [comment]
how about looking into the sourcode? https://github.com/hoppler/SoftEtherApi-PHP/blob/66ceb4f93f2d2c09f5a1a1cda0d5999e224fc5ac/SoftEtherApi/Api/SoftEtherHub.php#L415

My "syntax" was just an example

**Comment by mohammad-rj** [comment]
$user = $softEther->HubApi->getUser("vpn", "test5");
$user->name = "test6";
$softEther->HubApi->SetUser("vpn",$user);

you mean like this
but it not work !!

**Comment by hoppler** [comment]
SoftEther does not allow the change of the "name" itself therefore it does not work. You can change realname with it or other fields. it was just an example of how to edit a user.

**Comment by mohammad-rj** [comment]
dear brother
I knew it from the beginning
And I asked you to create this feature

this may be
we can manually modify the user name from the softether configuration file

plz add this ability  to your useful api
